name: 'CI - Main'

on:
  workflow_dispatch:
    inputs:
      verbose:
        default: 'false'
        description: 'Verbose output'
        required: false
  push:
    paths-ignore:
      - '.github/**'
      - 'spring-cloud-dataflow-apps-plugin/**'
    branches:
      - 'main'

jobs:
  build:
    uses: ./.github/workflows/common.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      TMC_API_TOKEN: ${{ secrets.TMC_API_TOKEN }}
      GCP_CRED_JSON: ${{ secrets.GCP_CRED_JSON }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    with:
      branch: 'main'
      verbose: ${{ inputs.verbose == 'true' }}
      mavenThreads: '0.5C'
